export const RECEIVE_TRIPS = "RECEIVE_TRIPS";
export const ADD_TRIP = "ADD_TRIP";
export const EDIT_TRIP = "EDIT_TRIP";
export const REMOVE_TRIP = "REMOVE_TRIP";
export const SET_CURRENT_VIEW = "SET_CURRENT_VIEW";
export const EDIT_TRIP_IMAGE = "EDIT_TRIP_IMAGE";
export const SET_SELECTED_TRIP_ID = "SET_SELECTED_TRIP_ID";
export const REMOVE_SELECTED_TRIP_ID = "REMOVE_SELECTED_TRIP_ID";
